Dockerfile.template
Replace busybox patch with the full gnu patch to support netresearch/composer-patches-plugin to resolve https://github.com/composer/docker/issues/47
=> Update dockerfile.template to add gnu patch

1.4/Dockerfile, 1.5/Dockerfile, 1.6/Dockerfile, Dockerfile.template
`curl` and `openssl` are already included in the base image.
`patch` was already in the template, but has not yet been applied to the Dockerfiles.
=> Remove unused or redundant dependencies

1.8/Dockerfile, 1.9/Dockerfile, Dockerfile.template
To streamline the code style with other docker library images
=> Update code style

1.10/Dockerfile
=> Update to 1.10.16

2.0/Dockerfile
=> Stable 2.0.0 release

2.0/Dockerfile
=> Release 2.0.1

2.0/Dockerfile
=> Composer 2.0.3

2.0/Dockerfile
Hi, I saw an update was available for Composer. This pull request upgrades the version of Composer being used in the Dockerfile from 2.0.3 to 2.0.4.
This fixes #144
=> Composer 2.0.4

1.10/Dockerfile
=> release 1.10.23

2.1/Dockerfile
=> release 2.1.9

2.1/Dockerfile
=> Composer 2.1.10

2.1/Dockerfile
=> release 2.1.11

1.10/Dockerfile, 2.1/Dockerfile
@tianon would this achieve the desired effect / outcome?
=> skip mercurial on i386 builds

.github/workflows/v2.yaml, 2.2/Dockerfile, 2.2/docker-entrypoint.sh
=> add 2.2 RC builds

2.2/Dockerfile, 2.3/Dockerfile
Fixes #247 and #246
This is more urgent for us due to https://github.com/composer/composer/pull/10920 to which is included in 2.3.9
=> Update to composer 2.3.9 and 2.2.16.

.github/workflows/v2.yaml, 2.4/Dockerfile, 2.4/docker-entrypoint.sh
Hi!
Composer 2.4 is released and includes very useful `audit` command, so it would be great to start publishing 2.4 images
https://blog.packagist.com/composer-2-4/
Closes https://github.com/composer/docker/issues/256
=> Add composer 2.4 image

2.6/Dockerfile, 2.6/docker-entrypoint.sh
Fixes #291.
💁‍♂️ Not sure what needs to be done here - I ran
```shell
cp -r 2.5 2.6
```
and adjusted the version in `2.6/Dockerfile`.
=> Enhancement: Prepare release for `2.6.0`

2.6/Dockerfile
=> Enhancement: Prepare release for `2.6.1`

.github/workflows/v2.yaml
=> Enhancement: Use matrix to reduce duplication

.github/workflows/v2.yaml
=> Fix: Configure working directory for steps that need it

.github/workflows/shellcheck.yaml, .github/workflows/v1.yaml, .github/workflows/v2.yaml
💁‍♂️ Probably better to find out about build failures before merging into `main`!
=> Enhancement: Run builds on pushes to pull requests

2.6/Dockerfile
=> Enhancement: Prepare release for 2.6.2

.github/workflows/shellcheck.yaml, .github/workflows/v1.yaml, .github/workflows/v2.yaml
=> Fix: Consistently indent with 2 spaces

2.6/Dockerfile
=> Enhancement: Prepare release for `2.6.3`

1.10/Dockerfile
=> Enhancement: Prepare release for `1.10.27`

2.6/Dockerfile
=> Enhancement: Prepare release for `2.6.4`

2.2/Dockerfile
=> Enhancement: Prepare release for `2.2.22`

2.2/Dockerfile
=> Enhancement: Prepare release for `2.2.23`

.github/workflows/v2-current.yaml, .github/workflows/v2-previous.yaml, 2.7/Dockerfile, 2.7/docker-entrypoint.sh
=> Enhancement: Prepare release for `2.7.1`

.github/workflows/v1.yaml, .github/workflows/v2-current.yaml, .github/workflows/v2-lts.yaml, .github/workflows/v2-previous.yaml
💁‍♂️ For reference, see 
- https://github.com/docker/login-action/compare/v1...v3
- https://github.com/docker/login-action/compare/v2...v3
=> Enhancement: Update `docker/login-action`

.github/workflows/shellcheck.yaml, .github/workflows/v1.yaml, .github/workflows/v2-current.yaml, .github/workflows/v2-lts.yaml, .github/workflows/v2-previous.yaml
💁‍♂️ For reference, see https://github.com/actions/checkout/compare/v3...v4.
=> Enhancement: Update `actions/checkout`

2.2/Dockerfile
=> Release 2.2.24

latest/Dockerfile
=> Enhancement: Update `composer/composer`

latest/Dockerfile
Fixes #345
See also https://github.com/composer/composer/releases/tag/2.8.0
=> release 2.8.0

latest/Dockerfile
=> Release 2.8.1

latest/Dockerfile
=> release 2.8.8

latest/Dockerfile
=> Release 2.8.9
